if: "branch = master"

language: php
os:
  - linux
dist: bionic

php:
  - "7.4"
  - "8.0"
  - "8.1"

cache:
  directories:
    - "${HOME}/.composer/cache"

install:
  - travis_retry composer update --no-interaction --optimize-autoloader

script:
  - XDEBUG_MODE=coverage phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  - email: false
